#!/usr/bin/env bash

## #ddev-generated: If you want to edit and own this file, remove this line.
## Description: Launch a browser with Dbgate
## Usage: dbgate
## Example: "ddev dbgate"

DDEV_DBGATE_PORT=8048
DDEV_DBGATE_HTTPS_PORT=8049

if [ ${DDEV_PRIMARY_URL%://*} = "http" ] || [ -n "${GITPOD_WORKSPACE_ID:-}" ] || [ "${CODESPACES:-}" = "true" ]; then
    # Gitpod: "gp preview" opens a blank page for Dbgate, use "xdg-open" instead
    if [ "${OSTYPE:-}" = "linux-gnu" ] && [ -n "${GITPOD_WORKSPACE_ID:-}" ] && [ -z "${DDEV_DEBUG:-}" ]; then
        xdg-open "$(DDEV_DEBUG=true ddev launch :$DDEV_DBGATE_PORT | grep "FULLURL" | awk '{print $2}')"
    else
        ddev launch :$DDEV_DBGATE_PORT
    fi
else
    ddev launch :$DDEV_DBGATE_HTTPS_PORT
fi
